/****************************************************************************
** Interface definition generated for ActiveQt project
**
**     'C:\Users\Chen-Liu\Documents\qtFrame\Win32\Debug\paintFrame.dll'
**
** Created:  周五 二月 23 11:23:55 2018
**
** WARNING! All changes made in this file will be lost!
****************************************************************************/

import "ocidl.idl";
#include <olectl.h>

[
	uuid(F294DC09-C77D-42EC-9505-E45CFE8A5363),
	version(1.00),
	helpstring("paintFrame 1.00 Type Library")
]
library paintFrameLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	/************************************************************************
	** If this causes a compile error in MIDL you need to upgrade the
	** Platform SDK you are using. Download the SDK from msdn.microsoft.com
	** and make sure that both the system and the Visual Studio environment
	** use the correct files.
	**
	************************************************************************/

	[uuid(34030F30-E359-4FE6-AB82-39766F5D91EE)]
	struct QRect {
		int left;
		int top;
		int right;
		int bottom;
	};

	[uuid(CB5F84B3-29E5-491D-BA18-5472488EEFBA)]
	struct QSize {
		int width;
		int height;
	};

	[uuid(3BE838A3-3FAC-BFC4-4C6C-37C44D030252)]
	struct QPoint {
		int x;
		int y;
	};

	/* Forward declaration of classes that might be used as parameters */

	coclass PaintFrame;


	enum MousePointer {
		ArrowCursor             = 0,
		UpArrowCursor           = 1,
		CrossCursor             = 2,
		WaitCursor              = 3,
		IBeamCursor             = 4,
		SizeVerCursor           = 5,
		SizeHorCursor           = 6,
		SizeBDiagCursor         = 7,
		SizeFDiagCursor         = 8,
		SizeAllCursor           = 9,
		BlankCursor             = 10,
		SplitVCursor            = 11,
		SplitHCursor            = 12,
		PointingHandCursor      = 13,
		ForbiddenCursor         = 14,
		WhatsThisCursor         = 15,
		BusyCursor	= 16
	};

	enum FocusPolicy {
		NoFocus             = 0,
		TabFocus            = 1,
		ClickFocus          = 2,
		StrongFocus         = 11,
		WheelFocus          = 15
	};


	[
		uuid(9D7D1AAB-FDAA-4C4B-AFBE-49CFA7D2F809),
		helpstring("PaintFrame Interface")
	]
	dispinterface IPaintFrame
	{
	properties:

	methods:
	};

	[
		uuid(713BE417-3E13-4B09-B5B0-DFAFCFA8A3F9),
		helpstring("PaintFrame Events Interface")
	]
	dispinterface IPaintFrameEvents
	{
	properties:
	methods:
	};

	[
		aggregatable,
		helpstring("PaintFrame Class"),
		version(1.0),
		uuid(CA1B8154-64AA-4A2A-B222-4F57117CA04C), 
		control
	]
	coclass PaintFrame
	{
		[default] dispinterface IPaintFrame;
		[default, source] dispinterface IPaintFrameEvents;
	};
};
